### PR TITLE
adding level to all kg nodes for hierarchy graph view

### PR DESCRIPTION
**Pull request by maximusunc**
#6 fix bug where some nodes don't get assigned a "level" and the page crashes when trying to activate hierarchical view.

### CODE REVIEW

**Comment by patrickkwang** [comment]
It looks like there was already a "level", and you're changing how it's determined. Can you explain more about what this changes does and why?

**Comment by maximusunc** [comment]
To use the hierarchical view, each node in the graph needs to have a "level" property. In old Robokop message format, it looks like all nodes either had a type array or a label with no type, so as far as I can tell we were always going into the if block at the bottom of this annotatedPrunedKnowledgeGraph function. That message format is no longer the case, and we need to handle level differently. So I moved the level property logic up to where we're already mapping over all kg nodes and results and I'm finding the query graph index that each kg node corresponds to.

This could potentially prove unintuitive if one kg node corresponds with multiple qg nodes in different results, but the kg node will at least have one "level" and the viewable graph might just look weird.

**Review by patrickkwang — COMMENTED** [review]
Miscellaneous comment. Can we flip around the if statement at line 117 so that we abort if the query graph is empty, and unindent everything by two spaces?

More general miscellaneous comment. This seems like a lot of work. Maybe it just looks like a lot and can be made more readable, or maybe it's over-complicated just to enable smart pruning. Either way this method may be a place to spend some more time.

**Comment by maximusunc** [comment]
Just opened an issue for improving that function, because I agree that it can probably be better.

**Review by patrickkwang — APPROVED** [review]

**Review by alongreyber — APPROVED** [review]

**Pull request merged**
